import {
  Button,
  ButtonGroup,
  Card,
  CardBody,
  CardFooter,
  Divider,
  Flex,
  Heading,
  Image,
  ListItem,
  Stack,
  Text,
  UnorderedList,
} from "@chakra-ui/react";

function AdrielleCard() {
  return (
    <Card maxW="750px">
      <CardBody>
        <Stack mt="6" spacing="3">
          <Heading size="lg">Adrielle website</Heading>
          <Image
            src="/adrielle.png"
            alt="Green double couch with wooden legs"
            borderRadius="lg"
          />
          <Heading size="md">Description</Heading>
          <Text>
            <Text as="b" color="blue.700">
              Adrielle
            </Text>{" "}
            is a demo e-commerce website of women`s shoes.
          </Text>
          <Text>
            This project is a{" "}
            <Text as="b" color="blue.700">
              demo for my portofolio
            </Text>{" "}
            and it can do the following main tasks:
          </Text>
          <UnorderedList>
            <ListItem>
              <Text as="b" color="blue.700">
                CRUD
              </Text>{" "}
              actions expected in an e-commerce website: fetch products, add or
              remove from favorites and cart, write a review or make an order.
            </ListItem>
            <ListItem>
              <Text as="b" color="blue.700">
                Supabase
              </Text>{" "}
              is used for data fetching and manipulation.
            </ListItem>
            <ListItem>
              Show and edit{" "}
              <Text as="b" color="blue.700">
                user`s details
              </Text>{" "}
              such as delivery address, personal orders and reviews.
            </ListItem>
            <ListItem>
              Authenticate users with{" "}
              <Text as="b" color="blue.700">
                NextAuth
              </Text>{" "}
              with{" "}
              <Text as="b" color="blue.700">
                Google Provider
              </Text>
              .
            </ListItem>
            <ListItem>
              <Text as="b" color="blue.700">
                Save
              </Text>{" "}
              products from favorites and cart if any of user before he logged
              in and transfer{" "}
              <Text as="b" color="blue.700">
                to user account
              </Text>
              .
            </ListItem>
            <ListItem>
              <Text as="b" color="blue.700">
                Light/dark mode
              </Text>
              .
            </ListItem>
          </UnorderedList>
          <Heading size="md">Notes</Heading>
          <UnorderedList>
            <ListItem>
              Text and images used in this project were created and generated by{" "}
              <Text as="b" color="blue.700">
                ChatGPT
              </Text>{" "}
              and{" "}
              <Text as="b" color="blue.700">
                OpenArt
              </Text>
              .
            </ListItem>
            <ListItem>
              As it is a{" "}
              <Text as="b" color="blue.700">
                demo project
              </Text>{" "}
              for my portofolio, I recommend using{" "}
              <Text as="b" color="blue.700">
                fake personal data
              </Text>{" "}
              such as telephone number and address.
            </ListItem>
          </UnorderedList>
        </Stack>
      </CardBody>
      <Divider />
      <CardFooter>
        <ButtonGroup spacing="2">
          <a href="https://adrielle.vercel.app/" target="_blank">
            <Button variant="solid" colorScheme="orange">
              Explore the website
            </Button>
          </a>

          <a href="https://github.com/IamAdri/adrielle" target="_blank">
            <Button variant="outline" colorScheme="orange">
              Explore github repository
            </Button>
          </a>
        </ButtonGroup>
      </CardFooter>
    </Card>
  );
}

export default AdrielleCard;
